#! /bin/bash

# $1: Optional path to a pacta sibling or its parent.

# Examples
# pacta-pull-origin-master
# pacta-pull-origin-master ~/git/pacta-data

source pacta-utils

here=$(pwd)
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"

path="${1:-$(pwd)}"
repos="$(pacta-find $path)"
for repo in $repos
do
    cd "$repo"
    green "$(basename $repo)"
    git checkout master
    git pull origin master
    echo

    git log  --pretty='%h % %s (%cr) <%an>' | head -1
    echo
done

cd "$here"
git checkout "$branch" 2>/dev/null

exit 0
